export interface ClassicCocktailSpec {
  id: string;
  name: string;
  spiritBase: string; // Bourbon, Rye, Gin, Tequila, Mezcal, Rum, Vodka, Brandy, Amaro, Low-ABV
  flavorProfile: 'boozy' | 'sour' | 'bitter' | 'highball' | 'tiki' | 'herbal' | 'dessert';
  glassware: string;
  ice: string;
  technique: string;
  ingredients: {
    name: string;
    amount: string;
    unit?: string;
    optional?: boolean;
  }[];
  instructions: string[];
  garnish?: string;
  description: string;
}

export const BAR_STAPLES = [
  'Angostura Bitters',
  'Orange Bitters',
  'Peychaud\'s Bitters',
  'Simple Syrup',
  'Rich Simple Syrup',
  'Demerara Syrup',
  'Honey Syrup',
  'Agave Nectar',
  'Fresh Lemon Juice',
  'Fresh Lemon',
  'Fresh Lime Juice',
  'Fresh Lime',
  'Fresh Orange',
  'Fresh Mint',
  'Club Soda',
  'Tonic Water',
  'Ginger Beer',
  'Sweet Vermouth',
  'Dry Vermouth',
  'Campari',
  'Triple Sec',
  'Cointreau',
  'Ice',
];

export function isRecognizedBarStaple(name: string): boolean {
  const norm = name.toLowerCase().trim();
  return BAR_STAPLES.some((s) => norm.includes(s.toLowerCase()) || s.toLowerCase().includes(norm));
}

export const CLASSIC_COCKTAILS: ClassicCocktailSpec[] = [
  {
    id: 'old-fashioned',
    name: 'Old Fashioned',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Rocks / Old Fashioned Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'Bourbon or Rye Whiskey', amount: '2', unit: 'oz' },
      { name: 'Demerara Syrup or Sugar Cube', amount: '0.25', unit: 'oz' },
      { name: 'Angostura Bitters', amount: '2-3', unit: 'dashes' },
      { name: 'Orange Peel', amount: '1', unit: 'twist', optional: true },
    ],
    instructions: [
      'Add syrup and bitters into a mixing glass or directly into a rocks glass.',
      'Add whiskey and a large block of ice.',
      'Stir gently for 30 seconds until properly chilled and diluted.',
      'Express the oil of an orange peel over the top and drop it in.',
    ],
    garnish: 'Expressed Orange Peel & Luxardo Cherry',
    description: 'The archetype of the cocktail—rich, spirit-forward, and timeless.',
  },
  {
    id: 'negroni',
    name: 'Negroni',
    spiritBase: 'Gin',
    flavorProfile: 'bitter',
    glassware: 'Rocks Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'London Dry Gin', amount: '1', unit: 'oz' },
      { name: 'Campari', amount: '1', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
      { name: 'Orange Peel', amount: '1', unit: 'slice/twist', optional: true },
    ],
    instructions: [
      'Combine gin, Campari, and sweet vermouth in a mixing glass with ice.',
      'Stir for 30 seconds until chilled and silky.',
      'Strain into a rocks glass over a fresh large ice cube.',
      'Garnish with an expressed orange peel.',
    ],
    garnish: 'Orange Peel or Orange Wheel',
    description: 'The golden ratio of equal parts—bitter, botanical, and bittersweet.',
  },
  {
    id: 'manhattan',
    name: 'Manhattan',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Coupe or Nick & Nora',
    ice: 'Served Up (Chilled)',
    technique: 'Stirred',
    ingredients: [
      { name: 'Rye or Bourbon Whiskey', amount: '2', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
      { name: 'Angostura Bitters', amount: '2', unit: 'dashes' },
    ],
    instructions: [
      'Combine rye, sweet vermouth, and bitters in a mixing glass with ice.',
      'Stir until thoroughly chilled (approx. 30 seconds).',
      'Strain into a chilled coupe or Nick & Nora glass.',
      'Garnish with a brandied cherry.',
    ],
    garnish: 'Luxardo Brandied Cherry',
    description: 'Elegance in a glass—warming rye spice married with rich botanicals.',
  },
  {
    id: 'margarita',
    name: 'Margarita',
    spiritBase: 'Tequila / Mezcal',
    flavorProfile: 'sour',
    glassware: 'Coupe or Rocks Glass',
    ice: 'Fresh Ice or Served Up',
    technique: 'Shaken',
    ingredients: [
      { name: 'Blanco Tequila', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '1', unit: 'oz' },
      { name: 'Cointreau or Triple Sec', amount: '0.75', unit: 'oz' },
      { name: 'Agave Nectar', amount: '0.25', unit: 'oz', optional: true },
    ],
    instructions: [
      'Optional: Run a lime wedge around half the rim of a coupe and dip into kosher salt.',
      'Add tequila, lime juice, Cointreau, and agave into a cocktail shaker with ice.',
      'Shake vigorously for 12-15 seconds until the shaker frosts over.',
      'Fine strain into the prepared glass.',
    ],
    garnish: 'Salt Rim & Fresh Lime Wheel',
    description: 'Crisp, punchy, and vibrant agave-lime harmony.',
  },
  {
    id: 'daiquiri',
    name: 'Classic Daiquiri',
    spiritBase: 'Rum',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'White Rum', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Combine rum, fresh lime juice, and simple syrup in a shaker with plenty of ice.',
      'Shake vigorously for 15 seconds.',
      'Double strain into a chilled coupe.',
    ],
    garnish: 'Lime Wheel or Float',
    description: 'The purest test of a bartender—crisp rum elevated by tart citrus and sweetness.',
  },
  {
    id: 'last-word',
    name: 'The Last Word',
    spiritBase: 'Gin',
    flavorProfile: 'herbal',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'Gin', amount: '0.75', unit: 'oz' },
      { name: 'Green Chartreuse', amount: '0.75', unit: 'oz' },
      { name: 'Maraschino Liqueur (Luxardo)', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add all four ingredients in equal parts into a shaker with ice.',
      'Shake vigorously for 15 seconds.',
      'Fine strain into a chilled coupe glass.',
    ],
    garnish: 'Luxardo Cherry or Lime Twist',
    description: 'Prohibition-era masterpiece—herbaceous, tart, and deeply complex.',
  },
  {
    id: 'paper-plane',
    name: 'Paper Plane',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'bitter',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'Bourbon Whiskey', amount: '0.75', unit: 'oz' },
      { name: 'Aperol', amount: '0.75', unit: 'oz' },
      { name: 'Amaro Nonino Quintessentia', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add bourbon, Aperol, Amaro Nonino, and fresh lemon juice to a shaker with ice.',
      'Shake hard for 15 seconds.',
      'Fine strain into a chilled coupe.',
    ],
    garnish: 'Mini paper airplane or Lemon Twist',
    description: 'Modern classic created by Sam Ross—bright bittersweet citrus with bourbon warmth.',
  },
  {
    id: 'espresso-martini',
    name: 'Espresso Martini',
    spiritBase: 'Vodka',
    flavorProfile: 'dessert',
    glassware: 'Coupe or Martini Glass',
    ice: 'Served Up (Frothy)',
    technique: 'Shaken Hard',
    ingredients: [
      { name: 'Vodka', amount: '1.5', unit: 'oz' },
      { name: 'Coffee Liqueur (Kahlúa or Mr Black)', amount: '1', unit: 'oz' },
      { name: 'Freshly Brewed Espresso', amount: '1', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.25', unit: 'oz', optional: true },
    ],
    instructions: [
      'Combine vodka, coffee liqueur, fresh hot espresso, and syrup in a shaker filled with ice.',
      'Shake exceptionally hard for 20 seconds to build thick microfoam crema.',
      'Fine strain into a chilled coupe glass.',
    ],
    garnish: '3 Roasted Coffee Beans (Health, Wealth & Happiness)',
    description: 'Velvety, energizing, and rich with a signature crema foam head.',
  },
  {
    id: 'mai-tai',
    name: '1944 Mai Tai',
    spiritBase: 'Rum',
    flavorProfile: 'tiki',
    glassware: 'Double Old Fashioned / Tiki Mug',
    ice: 'Crushed Ice',
    technique: 'Shaken',
    ingredients: [
      { name: 'Aged Jamaican Rum', amount: '1', unit: 'oz' },
      { name: 'Martinique Rhum Agricole or Dark Rum', amount: '1', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Orange Curaçao or Triple Sec', amount: '0.5', unit: 'oz' },
      { name: 'Orgeat (Almond Syrup)', amount: '0.5', unit: 'oz' },
    ],
    instructions: [
      'Add rums, lime juice, curaçao, and orgeat into a shaker with crushed ice.',
      'Shake vigorously for 10 seconds.',
      'Pour entire contents unstrained into a double rocks glass or tiki mug.',
      'Top with more crushed ice and slap a fresh mint sprig before garnishing.',
    ],
    garnish: 'Spent Lime Shell & Mint Bouquet (Island & Palm Tree)',
    description: 'The crown jewel of Tiki culture—nutty, tart, and rum-forward.',
  },
  {
    id: 'french-75',
    name: 'French 75',
    spiritBase: 'Gin',
    flavorProfile: 'highball',
    glassware: 'Champagne Flute or Coupe',
    ice: 'Served Up / Chilled',
    technique: 'Shaken & Topped',
    ingredients: [
      { name: 'Gin', amount: '1', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.5', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.5', unit: 'oz' },
      { name: 'Champagne or Dry Sparkling Wine', amount: '2.5', unit: 'oz' },
    ],
    instructions: [
      'Shake gin, lemon juice, and simple syrup with ice.',
      'Strain into a chilled champagne flute.',
      'Top gently with dry champagne or Prosecco.',
    ],
    garnish: 'Lemon Twist Ribbon',
    description: 'Effervescent and celebratory—hits with the power of a French 75mm field gun.',
  },
  {
    id: 'boulevardier',
    name: 'Boulevardier',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Rocks Glass or Coupe',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'Bourbon or Rye Whiskey', amount: '1.25', unit: 'oz' },
      { name: 'Campari', amount: '1', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
    ],
    instructions: [
      'Combine whiskey, Campari, and sweet vermouth in a mixing glass with ice.',
      'Stir until chilled and properly diluted (30 seconds).',
      'Strain into a rocks glass over a large ice cube or into a chilled coupe.',
    ],
    garnish: 'Orange Twist or Brandied Cherry',
    description: 'The whiskey lover\'s Negroni—warm, bittersweet, and deeply comforting.',
  },
  {
    id: 'paloma',
    name: 'Classic Paloma',
    spiritBase: 'Tequila / Mezcal',
    flavorProfile: 'highball',
    glassware: 'Highball / Collins Glass',
    ice: 'Fresh Cubed Ice',
    technique: 'Built in Glass',
    ingredients: [
      { name: 'Blanco Tequila', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.5', unit: 'oz' },
      { name: 'Grapefruit Soda (Jarritos, Squirt, or Fever-Tree)', amount: '3-4', unit: 'oz' },
      { name: 'Pinch of Sea Salt', amount: '1', unit: 'pinch', optional: true },
    ],
    instructions: [
      'Salt the rim of a tall highball glass if desired.',
      'Fill glass with fresh ice cubes.',
      'Add tequila, lime juice, and a pinch of salt.',
      'Top with grapefruit soda and stir gently once to integrate.',
    ],
    garnish: 'Grapefruit Wedge & Salt Rim',
    description: 'Mexico\'s most beloved cocktail—refreshingly tart, fizzy, and thirst-quenching.',
  },
  {
    id: 'gimlet',
    name: 'Classic Gimlet',
    spiritBase: 'Gin',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'London Dry Gin', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add gin, fresh lime juice, and simple syrup into a shaker with ice.',
      'Shake vigorously for 15 seconds.',
      'Fine strain into a chilled coupe.',
    ],
    garnish: 'Lime Wheel',
    description: 'Sharp, brisk, and botanical perfection.',
  },
  {
    id: 'corpse-reviver-2',
    name: 'Corpse Reviver #2',
    spiritBase: 'Gin',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up',
    technique: 'Shaken',
    ingredients: [
      { name: 'Gin', amount: '0.75', unit: 'oz' },
      { name: 'Lillet Blanc or Cocchi Americano', amount: '0.75', unit: 'oz' },
      { name: 'Cointreau or Triple Sec', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
      { name: 'Absinthe', amount: '1', unit: 'rinse' },
    ],
    instructions: [
      'Rinse a chilled coupe glass with a splash of absinthe and dump the excess.',
      'Add gin, Lillet Blanc, Cointreau, and lemon juice into a shaker with ice.',
      'Shake hard for 15 seconds and strain into the absinthe-rinsed coupe.',
    ],
    garnish: 'Lemon Twist or Brandied Cherry',
    description: 'Legendary cure-all—bright citrus with an enchanting anise perfume.',
  },
  {
    id: 'whiskey-sour',
    name: 'Boston Whiskey Sour',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'sour',
    glassware: 'Coupe or Rocks Glass',
    ice: 'Served Up or on Rocks',
    technique: 'Dry Shake & Hard Shake',
    ingredients: [
      { name: 'Bourbon or Rye Whiskey', amount: '2', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.75', unit: 'oz' },
      { name: 'Egg White (or Aquafaba)', amount: '0.5', unit: 'oz', optional: true },
      { name: 'Angostura Bitters', amount: '2-3', unit: 'drops for foam' },
    ],
    instructions: [
      'Add whiskey, lemon juice, simple syrup, and egg white to a shaker without ice.',
      'Dry shake vigorously for 15 seconds to emulsify egg white into foam.',
      'Add ice and shake hard for another 15 seconds until frosty.',
      'Fine strain into a chilled coupe. Dot surface with Angostura bitters.',
    ],
    garnish: 'Angostura Bitters Drops & Lemon Wheel',
    description: 'Velvety, creamy citrus foam balancing rich bourbon warmth.',
  },
  {
    id: 'sazerac',
    name: 'New Orleans Sazerac',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Rocks Glass',
    ice: 'Served Neat (No Ice)',
    technique: 'Stirred & Absinthe Rinse',
    ingredients: [
      { name: 'Rye Whiskey (or Cognac)', amount: '2', unit: 'oz' },
      { name: 'Demerara Syrup or Sugar Cube', amount: '0.25', unit: 'oz' },
      { name: 'Peychaud\'s Bitters', amount: '3-4', unit: 'dashes' },
      { name: 'Angostura Bitters', amount: '1', unit: 'dash' },
      { name: 'Absinthe or Herbsaint', amount: '1', unit: 'rinse' },
    ],
    instructions: [
      'Rinse a chilled rocks glass with absinthe and discard excess.',
      'In a mixing glass with ice, stir rye, syrup, and both bitters for 30 seconds.',
      'Strain into the prepared absinthe-rinsed glass.',
      'Express lemon peel oils over the glass and discard the peel.',
    ],
    garnish: 'Expressed Lemon Peel (Discarded)',
    description: 'America\'s oldest cocktail—an aromatic New Orleans icon of rye, anise, and creole bitters.',
  },
  {
    id: 'penicillin',
    name: 'Penicillin',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'sour',
    glassware: 'Rocks Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Shaken with Islay Float',
    ingredients: [
      { name: 'Blended Scotch or Bourbon Whiskey', amount: '2', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
      { name: 'Honey-Ginger Syrup', amount: '0.75', unit: 'oz' },
      { name: 'Smoky Islay Scotch or Mezcal', amount: '0.25', unit: 'oz float' },
    ],
    instructions: [
      'Combine whiskey, lemon juice, and honey-ginger syrup in a shaker with ice.',
      'Shake vigorously and strain into a rocks glass over a large ice cube.',
      'Gently float the smoky scotch over the back of a bar spoon on top.',
    ],
    garnish: 'Candied Ginger or Lemon Wheel',
    description: 'Modern craft legend created by Sam Ross—spicy ginger, tart lemon, and rich peat smoke.',
  },
  {
    id: 'jungle-bird',
    name: 'Jungle Bird',
    spiritBase: 'Rum',
    flavorProfile: 'bitter',
    glassware: 'Rocks Glass or Tiki Mug',
    ice: 'Crushed Ice',
    technique: 'Shaken Hard',
    ingredients: [
      { name: 'Dark or Blackstrap Rum', amount: '1.5', unit: 'oz' },
      { name: 'Campari', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Pineapple Juice', amount: '1.5', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.5', unit: 'oz' },
      { name: 'Demerara Syrup', amount: '0.5', unit: 'oz' },
    ],
    instructions: [
      'Add dark rum, Campari, pineapple juice, lime juice, and syrup into a shaker with ice.',
      'Shake vigorously for 15 seconds to create a frothy pineapple crema.',
      'Strain into a rocks glass filled with crushed ice.',
    ],
    garnish: 'Pineapple Fronds & Maraschino Cherry',
    description: '1970s Malaysian tiki masterpiece—where dark molasses rum meets bitter Italian Campari.',
  },
  {
    id: 'oaxacan-old-fashioned',
    name: 'Oaxacan Old Fashioned',
    spiritBase: 'Tequila / Mezcal',
    flavorProfile: 'boozy',
    glassware: 'Rocks Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'Reposado Tequila', amount: '1.5', unit: 'oz' },
      { name: 'Mezcal (Espadín)', amount: '0.5', unit: 'oz' },
      { name: 'Agave Nectar', amount: '1', unit: 'barspoon' },
      { name: 'Angostura Bitters', amount: '2', unit: 'dashes' },
    ],
    instructions: [
      'Combine reposado, mezcal, agave nectar, and bitters in a mixing glass with ice.',
      'Stir for 30 seconds until chilled and integrated.',
      'Strain over a large ice block in a rocks glass. Express a flamed orange peel.',
    ],
    garnish: 'Flamed Orange Peel',
    description: 'Created at Death & Co in NYC—smoky mezcal and aged agave reimagining the Old Fashioned.',
  },
  {
    id: 'sidecar',
    name: 'Classic Sidecar',
    spiritBase: 'Brandy',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up',
    technique: 'Shaken',
    ingredients: [
      { name: 'Cognac or Brandy', amount: '2', unit: 'oz' },
      { name: 'Cointreau or Triple Sec', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Optional: Sugar half the rim of a chilled coupe glass.',
      'Add cognac, Cointreau, and lemon juice into a shaker with ice.',
      'Shake hard for 15 seconds and double strain into the prepared glass.',
    ],
    garnish: 'Sugar Rim & Orange Twist',
    description: 'Parisian 1920s classic—warming aged cognac balanced with crisp citrus and orange liqueur.',
  },
  {
    id: 'moscow-mule',
    name: 'Moscow Mule',
    spiritBase: 'Vodka',
    flavorProfile: 'highball',
    glassware: 'Copper Mug or Collins Glass',
    ice: 'Crushed Ice',
    technique: 'Built in Mug',
    ingredients: [
      { name: 'Vodka', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.5', unit: 'oz' },
      { name: 'Ginger Beer', amount: '4', unit: 'oz' },
    ],
    instructions: [
      'Fill a copper mug or highball glass with crushed ice.',
      'Add vodka and fresh lime juice.',
      'Top with spicy ginger beer and stir gently to combine.',
    ],
    garnish: 'Lime Wheel & Fresh Mint Sprig',
    description: 'Crisp, spicy ginger kick with icy refreshment.',
  },
  {
    id: 'tom-collins',
    name: 'Tom Collins',
    spiritBase: 'Gin',
    flavorProfile: 'highball',
    glassware: 'Collins / Highball Glass',
    ice: 'Fresh Cubed Ice',
    technique: 'Built / Shaken & Topped',
    ingredients: [
      { name: 'Old Tom or London Dry Gin', amount: '2', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '1', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.5', unit: 'oz' },
      { name: 'Club Soda', amount: '3-4', unit: 'oz' },
    ],
    instructions: [
      'Shake gin, lemon juice, and simple syrup with ice.',
      'Strain into a tall Collins glass filled with fresh ice cubes.',
      'Top with club soda and stir gently once.',
    ],
    garnish: 'Lemon Wheel & Maraschino Cherry',
    description: 'The definitive sparkling lemonade for adults—effervescent, crisp, and thirst-quenching.',
  },
  {
    id: 'clover-club',
    name: 'Clover Club',
    spiritBase: 'Gin',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up',
    technique: 'Dry Shake & Shaken',
    ingredients: [
      { name: 'Gin', amount: '2', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.5', unit: 'oz' },
      { name: 'Raspberry Syrup (or Grenadine)', amount: '0.5', unit: 'oz' },
      { name: 'Dry Vermouth', amount: '0.5', unit: 'oz', optional: true },
      { name: 'Egg White', amount: '0.5', unit: 'oz' },
    ],
    instructions: [
      'Add all ingredients into a shaker without ice and dry shake for 15 seconds.',
      'Add ice and shake hard for 15 seconds until chilled.',
      'Fine strain into a chilled coupe.',
    ],
    garnish: 'Fresh Raspberries or Mint Leaf',
    description: 'Pre-prohibition gentleman\'s club cocktail—silky pink foam with berry tartness.',
  },
  {
    id: 'aperol-spritz',
    name: 'Aperol Spritz (3-2-1)',
    spiritBase: 'Any',
    flavorProfile: 'highball',
    glassware: 'Wine Glass',
    ice: 'Cubed Ice',
    technique: 'Built in Glass',
    ingredients: [
      { name: 'Prosecco or Sparkling Wine', amount: '3', unit: 'oz' },
      { name: 'Aperol', amount: '2', unit: 'oz' },
      { name: 'Club Soda', amount: '1', unit: 'oz' },
    ],
    instructions: [
      'Fill a large wine glass with ice.',
      'Add Prosecco first, followed by Aperol in an equal circular motion.',
      'Top with a splash of club soda and gently stir.',
    ],
    garnish: 'Fresh Orange Wheel & Green Olive',
    description: 'The golden hour aperitivo—effervescent, bittersweet, and light on alcohol.',
  },
];
