export interface ClassicCocktailSpec {
  id: string;
  name: string;
  spiritBase: string; // Bourbon, Rye, Gin, Tequila, Mezcal, Rum, Vodka, Brandy, Amaro, Low-ABV
  flavorProfile: 'boozy' | 'sour' | 'bitter' | 'highball' | 'tiki' | 'herbal' | 'dessert';
  glassware: string;
  ice: string;
  technique: string;
  ingredients: {
    name: string;
    amount: string;
    unit?: string;
    optional?: boolean;
  }[];
  instructions: string[];
  garnish?: string;
  description: string;
}

export const BAR_STAPLES = [
  'Angostura Bitters',
  'Orange Bitters',
  'Peychaud\'s Bitters',
  'Simple Syrup',
  'Rich Simple Syrup',
  'Demerara Syrup',
  'Honey Syrup',
  'Agave Nectar',
  'Fresh Lemon Juice',
  'Fresh Lemon',
  'Fresh Lime Juice',
  'Fresh Lime',
  'Fresh Orange',
  'Fresh Mint',
  'Club Soda',
  'Tonic Water',
  'Ginger Beer',
  'Sweet Vermouth',
  'Dry Vermouth',
  'Campari',
  'Triple Sec',
  'Cointreau',
  'Ice',
];

export function isRecognizedBarStaple(name: string): boolean {
  const norm = name.toLowerCase().trim();
  return BAR_STAPLES.some((s) => norm.includes(s.toLowerCase()) || s.toLowerCase().includes(norm));
}

export const CLASSIC_COCKTAILS: ClassicCocktailSpec[] = [
  {
    id: 'old-fashioned',
    name: 'Old Fashioned',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Rocks / Old Fashioned Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'Bourbon or Rye Whiskey', amount: '2', unit: 'oz' },
      { name: 'Demerara Syrup or Sugar Cube', amount: '0.25', unit: 'oz' },
      { name: 'Angostura Bitters', amount: '2-3', unit: 'dashes' },
      { name: 'Orange Peel', amount: '1', unit: 'twist', optional: true },
    ],
    instructions: [
      'Add syrup and bitters into a mixing glass or directly into a rocks glass.',
      'Add whiskey and a large block of ice.',
      'Stir gently for 30 seconds until properly chilled and diluted.',
      'Express the oil of an orange peel over the top and drop it in.',
    ],
    garnish: 'Expressed Orange Peel & Luxardo Cherry',
    description: 'The archetype of the cocktail—rich, spirit-forward, and timeless.',
  },
  {
    id: 'negroni',
    name: 'Negroni',
    spiritBase: 'Gin',
    flavorProfile: 'bitter',
    glassware: 'Rocks Glass',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'London Dry Gin', amount: '1', unit: 'oz' },
      { name: 'Campari', amount: '1', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
      { name: 'Orange Peel', amount: '1', unit: 'slice/twist', optional: true },
    ],
    instructions: [
      'Combine gin, Campari, and sweet vermouth in a mixing glass with ice.',
      'Stir for 30 seconds until chilled and silky.',
      'Strain into a rocks glass over a fresh large ice cube.',
      'Garnish with an expressed orange peel.',
    ],
    garnish: 'Orange Peel or Orange Wheel',
    description: 'The golden ratio of equal parts—bitter, botanical, and bittersweet.',
  },
  {
    id: 'manhattan',
    name: 'Manhattan',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Coupe or Nick & Nora',
    ice: 'Served Up (Chilled)',
    technique: 'Stirred',
    ingredients: [
      { name: 'Rye or Bourbon Whiskey', amount: '2', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
      { name: 'Angostura Bitters', amount: '2', unit: 'dashes' },
    ],
    instructions: [
      'Combine rye, sweet vermouth, and bitters in a mixing glass with ice.',
      'Stir until thoroughly chilled (approx. 30 seconds).',
      'Strain into a chilled coupe or Nick & Nora glass.',
      'Garnish with a brandied cherry.',
    ],
    garnish: 'Luxardo Brandied Cherry',
    description: 'Elegance in a glass—warming rye spice married with rich botanicals.',
  },
  {
    id: 'margarita',
    name: 'Margarita',
    spiritBase: 'Tequila / Mezcal',
    flavorProfile: 'sour',
    glassware: 'Coupe or Rocks Glass',
    ice: 'Fresh Ice or Served Up',
    technique: 'Shaken',
    ingredients: [
      { name: 'Blanco Tequila', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '1', unit: 'oz' },
      { name: 'Cointreau or Triple Sec', amount: '0.75', unit: 'oz' },
      { name: 'Agave Nectar', amount: '0.25', unit: 'oz', optional: true },
    ],
    instructions: [
      'Optional: Run a lime wedge around half the rim of a coupe and dip into kosher salt.',
      'Add tequila, lime juice, Cointreau, and agave into a cocktail shaker with ice.',
      'Shake vigorously for 12-15 seconds until the shaker frosts over.',
      'Fine strain into the prepared glass.',
    ],
    garnish: 'Salt Rim & Fresh Lime Wheel',
    description: 'Crisp, punchy, and vibrant agave-lime harmony.',
  },
  {
    id: 'daiquiri',
    name: 'Classic Daiquiri',
    spiritBase: 'Rum',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'White Rum', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Combine rum, fresh lime juice, and simple syrup in a shaker with plenty of ice.',
      'Shake vigorously for 15 seconds.',
      'Double strain into a chilled coupe.',
    ],
    garnish: 'Lime Wheel or Float',
    description: 'The purest test of a bartender—crisp rum elevated by tart citrus and sweetness.',
  },
  {
    id: 'last-word',
    name: 'The Last Word',
    spiritBase: 'Gin',
    flavorProfile: 'herbal',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'Gin', amount: '0.75', unit: 'oz' },
      { name: 'Green Chartreuse', amount: '0.75', unit: 'oz' },
      { name: 'Maraschino Liqueur (Luxardo)', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add all four ingredients in equal parts into a shaker with ice.',
      'Shake vigorously for 15 seconds.',
      'Fine strain into a chilled coupe glass.',
    ],
    garnish: 'Luxardo Cherry or Lime Twist',
    description: 'Prohibition-era masterpiece—herbaceous, tart, and deeply complex.',
  },
  {
    id: 'paper-plane',
    name: 'Paper Plane',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'bitter',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'Bourbon Whiskey', amount: '0.75', unit: 'oz' },
      { name: 'Aperol', amount: '0.75', unit: 'oz' },
      { name: 'Amaro Nonino Quintessentia', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add bourbon, Aperol, Amaro Nonino, and fresh lemon juice to a shaker with ice.',
      'Shake hard for 15 seconds.',
      'Fine strain into a chilled coupe.',
    ],
    garnish: 'Mini paper airplane or Lemon Twist',
    description: 'Modern classic created by Sam Ross—bright bittersweet citrus with bourbon warmth.',
  },
  {
    id: 'espresso-martini',
    name: 'Espresso Martini',
    spiritBase: 'Vodka',
    flavorProfile: 'dessert',
    glassware: 'Coupe or Martini Glass',
    ice: 'Served Up (Frothy)',
    technique: 'Shaken Hard',
    ingredients: [
      { name: 'Vodka', amount: '1.5', unit: 'oz' },
      { name: 'Coffee Liqueur (Kahlúa or Mr Black)', amount: '1', unit: 'oz' },
      { name: 'Freshly Brewed Espresso', amount: '1', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.25', unit: 'oz', optional: true },
    ],
    instructions: [
      'Combine vodka, coffee liqueur, fresh hot espresso, and syrup in a shaker filled with ice.',
      'Shake exceptionally hard for 20 seconds to build thick microfoam crema.',
      'Fine strain into a chilled coupe glass.',
    ],
    garnish: '3 Roasted Coffee Beans (Health, Wealth & Happiness)',
    description: 'Velvety, energizing, and rich with a signature crema foam head.',
  },
  {
    id: 'mai-tai',
    name: '1944 Mai Tai',
    spiritBase: 'Rum',
    flavorProfile: 'tiki',
    glassware: 'Double Old Fashioned / Tiki Mug',
    ice: 'Crushed Ice',
    technique: 'Shaken',
    ingredients: [
      { name: 'Aged Jamaican Rum', amount: '1', unit: 'oz' },
      { name: 'Martinique Rhum Agricole or Dark Rum', amount: '1', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Orange Curaçao or Triple Sec', amount: '0.5', unit: 'oz' },
      { name: 'Orgeat (Almond Syrup)', amount: '0.5', unit: 'oz' },
    ],
    instructions: [
      'Add rums, lime juice, curaçao, and orgeat into a shaker with crushed ice.',
      'Shake vigorously for 10 seconds.',
      'Pour entire contents unstrained into a double rocks glass or tiki mug.',
      'Top with more crushed ice and slap a fresh mint sprig before garnishing.',
    ],
    garnish: 'Spent Lime Shell & Mint Bouquet (Island & Palm Tree)',
    description: 'The crown jewel of Tiki culture—nutty, tart, and rum-forward.',
  },
  {
    id: 'french-75',
    name: 'French 75',
    spiritBase: 'Gin',
    flavorProfile: 'highball',
    glassware: 'Champagne Flute or Coupe',
    ice: 'Served Up / Chilled',
    technique: 'Shaken & Topped',
    ingredients: [
      { name: 'Gin', amount: '1', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.5', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.5', unit: 'oz' },
      { name: 'Champagne or Dry Sparkling Wine', amount: '2.5', unit: 'oz' },
    ],
    instructions: [
      'Shake gin, lemon juice, and simple syrup with ice.',
      'Strain into a chilled champagne flute.',
      'Top gently with dry champagne or Prosecco.',
    ],
    garnish: 'Lemon Twist Ribbon',
    description: 'Effervescent and celebratory—hits with the power of a French 75mm field gun.',
  },
  {
    id: 'boulevardier',
    name: 'Boulevardier',
    spiritBase: 'Bourbon / Rye',
    flavorProfile: 'boozy',
    glassware: 'Rocks Glass or Coupe',
    ice: 'Large Clear Ice Cube',
    technique: 'Stirred',
    ingredients: [
      { name: 'Bourbon or Rye Whiskey', amount: '1.25', unit: 'oz' },
      { name: 'Campari', amount: '1', unit: 'oz' },
      { name: 'Sweet Vermouth', amount: '1', unit: 'oz' },
    ],
    instructions: [
      'Combine whiskey, Campari, and sweet vermouth in a mixing glass with ice.',
      'Stir until chilled and properly diluted (30 seconds).',
      'Strain into a rocks glass over a large ice cube or into a chilled coupe.',
    ],
    garnish: 'Orange Twist or Brandied Cherry',
    description: 'The whiskey lover\'s Negroni—warm, bittersweet, and deeply comforting.',
  },
  {
    id: 'paloma',
    name: 'Classic Paloma',
    spiritBase: 'Tequila / Mezcal',
    flavorProfile: 'highball',
    glassware: 'Highball / Collins Glass',
    ice: 'Fresh Cubed Ice',
    technique: 'Built in Glass',
    ingredients: [
      { name: 'Blanco Tequila', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.5', unit: 'oz' },
      { name: 'Grapefruit Soda (Jarritos, Squirt, or Fever-Tree)', amount: '3-4', unit: 'oz' },
      { name: 'Pinch of Sea Salt', amount: '1', unit: 'pinch', optional: true },
    ],
    instructions: [
      'Salt the rim of a tall highball glass if desired.',
      'Fill glass with fresh ice cubes.',
      'Add tequila, lime juice, and a pinch of salt.',
      'Top with grapefruit soda and stir gently once to integrate.',
    ],
    garnish: 'Grapefruit Wedge & Salt Rim',
    description: 'Mexico\'s most beloved cocktail—refreshingly tart, fizzy, and thirst-quenching.',
  },
  {
    id: 'gimlet',
    name: 'Classic Gimlet',
    spiritBase: 'Gin',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up (Chilled)',
    technique: 'Shaken',
    ingredients: [
      { name: 'London Dry Gin', amount: '2', unit: 'oz' },
      { name: 'Fresh Lime Juice', amount: '0.75', unit: 'oz' },
      { name: 'Simple Syrup', amount: '0.75', unit: 'oz' },
    ],
    instructions: [
      'Add gin, fresh lime juice, and simple syrup into a shaker with ice.',
      'Shake vigorously for 15 seconds.',
      'Fine strain into a chilled coupe.',
    ],
    garnish: 'Lime Wheel',
    description: 'Sharp, brisk, and botanical perfection.',
  },
  {
    id: 'corpse-reviver-2',
    name: 'Corpse Reviver #2',
    spiritBase: 'Gin',
    flavorProfile: 'sour',
    glassware: 'Coupe Glass',
    ice: 'Served Up',
    technique: 'Shaken',
    ingredients: [
      { name: 'Gin', amount: '0.75', unit: 'oz' },
      { name: 'Lillet Blanc or Cocchi Americano', amount: '0.75', unit: 'oz' },
      { name: 'Cointreau or Triple Sec', amount: '0.75', unit: 'oz' },
      { name: 'Fresh Lemon Juice', amount: '0.75', unit: 'oz' },
      { name: 'Absinthe', amount: '1', unit: 'rinse' },
    ],
    instructions: [
      'Rinse a chilled coupe glass with a splash of absinthe and dump the excess.',
      'Add gin, Lillet Blanc, Cointreau, and lemon juice into a shaker with ice.',
      'Shake hard for 15 seconds and strain into the absinthe-rinsed coupe.',
    ],
    garnish: 'Lemon Twist or Brandied Cherry',
    description: 'Legendary cure-all—bright citrus with an enchanting anise perfume.',
  },
];
